package com.qiren.project.ui.core;

import com.qiren.project.pojo.Message;
import com.qiren.project.services.MessageService;
import com.qiren.project.services.ServiceBuilder;
import com.qiren.project.ui.AbstractPage;
import com.qiren.project.ui.MessageDetailPage;
import com.qiren.project.util.CoreUtils;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class MessagePage extends AbstractPage {
    private JPanel mainPanel;
    private JPanel listPanel;

    private MessageService messageService = ServiceBuilder.getInstance().build(MessageService.class);
    private List<Message> messages = new ArrayList<>();

    @Override
    public void pageInit(JFrame frame) {
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        String messageInfo = """
                <html>
                <b>Sender:&nbsp;</b>%replace1%<br>
                <b>Topic:&nbsp;</b>%replace2%<br>
                <b>Time:&nbsp;</b>%replace3%<br>
                </html>
                """;
        messages.addAll(messageService.getMyMessage());
        for (Message message : messages) {
            JPanel listItemPanel = new JPanel();
            listItemPanel.setLayout(new BoxLayout(listItemPanel, BoxLayout.X_AXIS));

            listItemPanel.add(new JLabel(
                    CoreUtils.customFormat(
                            messageInfo, message.getMessageFrom(), message.getTitle(), message.getTime())));
            JPanel buttonPanel = new JPanel();
            buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));

            JButton viewButton = new JButton("View Details");
            viewButton.addActionListener(e -> {
                JOptionPane.showMessageDialog(frame,
                        new MessageDetailPage(frame, message).getMainPanel(),
                        "View Detail",
                        JOptionPane.INFORMATION_MESSAGE);
            });
            buttonPanel.add(viewButton);

            listItemPanel.add(buttonPanel);

            listPanel.add(listItemPanel);
            listPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        }
    }

    @Override
    public String getTitle() {
        return "Message Box";
    }

    @Override
    public JPanel getPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        listPanel = new JPanel();
        listPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane1.setViewportView(listPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
