package com.qiren.project.ui;

import com.qiren.project.services.LoginService;
import com.qiren.project.services.ServiceBuilder;
import com.qiren.project.ui.core.Intend;
import com.qiren.project.ui.core.PageControlCenter;
import com.qiren.project.ui.core.PageRequest;
import com.qiren.project.util.CoreUtils;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;

public class LoginPage extends AbstractPage {

    private JPanel loginPanel;
    private JLabel welcomeLabel;
    private JPanel contentPanel;
    private JTextField emailField;
    private JPasswordField passwordField;
    private JButton studentLoginButton;
    private JButton staffLoginButton;

    private LoginService loginService;

    @Override
    public void pageInit(JFrame frame) {
        loginService = ServiceBuilder.getInstance().build(LoginService.class);
        staffLoginButton.addActionListener(e -> {
            if (!CoreUtils.checkEmail(emailField.getText())) {
                CoreUtils.showErrorDialog(frame, "Invalid Email Format!");
                return;
            }
            if (loginService.staffLogin(emailField.getText(),
                    new String(passwordField.getPassword()))) {
                PageControlCenter.getInstance().sendPageRequest(
                        new Intend(PageRequest.PAGE_CHANGE_REQUEST, "", PageRequest.MAIN_PAGE));
            } else {
                CoreUtils.showErrorDialog(frame, "Invalid Username or Password!");
            }
        });
        studentLoginButton.addActionListener(e -> {
            if (!CoreUtils.checkEmail(emailField.getText())) {
                CoreUtils.showErrorDialog(frame, "Invalid Email Format!");
                return;
            }
            if (loginService.studentLogin(emailField.getText(),
                    new String(passwordField.getPassword()))) {
                PageControlCenter.getInstance().sendPageRequest(
                        new Intend(PageRequest.PAGE_CHANGE_REQUEST, "", PageRequest.MAIN_PAGE));
            } else {
                CoreUtils.showErrorDialog(frame, "Invalid Username or Password!");
            }
        });
    }

    @Override
    public String getTitle() {
        return "Login Page";
    }

    @Override
    public JPanel getPanel() {
        return loginPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginPanel = new JPanel();
        loginPanel.setLayout(new BorderLayout(0, 0));
        welcomeLabel = new JLabel();
        welcomeLabel.setText("<html> <h2> Welcome to Northeastern University Course Management System! </h2> Please Login First </html>");
        loginPanel.add(welcomeLabel, BorderLayout.NORTH);
        contentPanel = new JPanel();
        contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1, false, true));
        loginPanel.add(contentPanel, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("<html> <b>Email:</b><br> Please enter your email here:<br> Just a remind that your email should follow Gmail Patterns<br> </html>");
        contentPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        emailField = new JTextField();
        contentPanel.add(emailField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("<html> <b>Password:</b><br> Please enter your password here:<br> Please make sure that your password has at least 6 letters.<br> </html>");
        contentPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        contentPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        passwordField = new JPasswordField();
        contentPanel.add(passwordField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        staffLoginButton = new JButton();
        staffLoginButton.setText("Staff Login");
        panel1.add(staffLoginButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studentLoginButton = new JButton();
        studentLoginButton.setText("Student Login");
        panel1.add(studentLoginButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPanel;
    }
}
