package com.qiren.project.ui;

import com.qiren.project.services.ServiceBuilder;
import com.qiren.project.services.UserService;
import com.qiren.project.ui.core.Intend;
import com.qiren.project.ui.core.PageControlCenter;
import com.qiren.project.ui.core.PageRequest;
import com.qiren.project.util.CoreUtils;

import javax.swing.*;
import java.awt.*;

public class MainPage extends AbstractPage {

    private UserService userService;

    private JPanel mainPanel;
    private JLabel noticeLabel;
    private JLabel courseLabel;
    private JButton courseButton;
    private JButton scheduleButton;
    private JPanel topPanel;
    private JPanel coursePanel;
    private JPanel schedulePanel;
    private JLabel scheduleLabel;
    private JButton studentButton;
    private JButton addStaffBtn;
    private JLabel lblAdmin2;
    private JLabel lblAdmin1;

    @Override
    public void pageInit(JFrame frame) {
        final String WELCOME_TITLE = "<html><h1>Good %replace%!</h1> <p>What would you like to do today?</p></html>";
        final String STAFF_VIEW_COURSE = "<html><b>View Courses:</b>" +
                "<br>You can manage all courses plans that belongs to you. " +
                "<br>You can view all courses and make a plan for them.</html>";
        final String STAFF_VIEW_SCHEDULE = "<html><b>View Schedule:</b>" +
                "<br>You can view or manage schedule that related to your courses.</html>";
        final String STUDENT_VIEW_COURSE = "<html><b>View Courses:</b>" +
                "<br>You can view or register all the courses." +
                "<br>You can view your grades of courses.</html>";
        final String STUDENT_VIEW_SCHEDULE = "<html><b>View Schedule:</b>" +
                "<br>You can view schedule that related to your courses.</html>";

        userService = ServiceBuilder.getInstance().build(UserService.class);
        noticeLabel.setText(
                WELCOME_TITLE.replace("%replace%",
                        CoreUtils.getTimeInDay() + ", " + userService.getUserName()));
        courseLabel.setText(userService.isStaff() ? STAFF_VIEW_COURSE : STUDENT_VIEW_COURSE);
        scheduleLabel.setText(userService.isStaff() ? STAFF_VIEW_SCHEDULE : STUDENT_VIEW_SCHEDULE);

        courseButton.addActionListener(e -> {
            if (userService.isStaff()) {
                sendPageChangeRequest(PageRequest.MAIN_PAGE, PageRequest.STAFF_COURSE_PAGE);
            } else {
                sendPageChangeRequest(PageRequest.MAIN_PAGE, PageRequest.STUDENT_COURSE_PAGE);
            }
        });
        scheduleButton.addActionListener(e -> {
            sendPageChangeRequest(PageRequest.MAIN_PAGE, PageRequest.VIEW_SCHEDULE_PAGE);
        });

        if (!userService.isAdmin()) {
            lblAdmin1.setVisible(false);
            lblAdmin2.setVisible(false);
            studentButton.setVisible(false);
            addStaffBtn.setVisible(false);
        } else {
            studentButton.addActionListener(e -> {
                Intend intend = new Intend(PageRequest.PAGE_CHANGE_REQUEST,
                        PageRequest.MAIN_PAGE, PageRequest.ACCOUNT_PAGE);
                intend.addExtra("type", "Student");
                PageControlCenter.getInstance().sendPageRequest(intend);
            });
            addStaffBtn.addActionListener(e -> {
                Intend intend = new Intend(PageRequest.PAGE_CHANGE_REQUEST,
                        PageRequest.MAIN_PAGE, PageRequest.ACCOUNT_PAGE);
                intend.addExtra("type", "Staff");
                PageControlCenter.getInstance().sendPageRequest(intend);
            });
        }
    }

    @Override
    public String getTitle() {
        return "Main Page";
    }

    @Override
    public JPanel getPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        topPanel = new JPanel();
        topPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(topPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        noticeLabel = new JLabel();
        noticeLabel.setText("<html><h1>Good Morning!</h1> <p>What would you like to do today?</p></html>");
        panel1.add(noticeLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        coursePanel = new JPanel();
        coursePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(coursePanel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scheduleLabel = new JLabel();
        scheduleLabel.setText("<html><b>View Schedule:</b><br>You can view or manage schedule that related to your courses.</html>");
        coursePanel.add(scheduleLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scheduleButton = new JButton();
        scheduleButton.setText("Continue");
        coursePanel.add(scheduleButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        schedulePanel = new JPanel();
        schedulePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(schedulePanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        courseLabel = new JLabel();
        courseLabel.setText("<html><b>View Courses:</b><br>You can manage all courses plans that belongs to you. <br>You can view all courses and make a plan for them.</html>");
        schedulePanel.add(courseLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        courseButton = new JButton();
        courseButton.setText("Continue");
        schedulePanel.add(courseButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblAdmin1 = new JLabel();
        lblAdmin1.setText("<html> <b>Add Student:</b><br> Add a new student account here<br> Only Dean's account can perform this<br> </html>");
        mainPanel.add(lblAdmin1, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studentButton = new JButton();
        studentButton.setText("Continue");
        mainPanel.add(studentButton, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblAdmin2 = new JLabel();
        lblAdmin2.setText("<html> <b>Add Staff:</b><br> Add a new staff account here<br> Only Dean's account can perform this<br> </html>");
        mainPanel.add(lblAdmin2, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addStaffBtn = new JButton();
        addStaffBtn.setText("Continue");
        mainPanel.add(addStaffBtn, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText(" ");
        mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
