package com.qiren.project.ui;

import com.qiren.project.pojo.CoursePlan;
import com.qiren.project.services.CoursePlanService;
import com.qiren.project.services.ServiceBuilder;
import com.qiren.project.services.UserService;
import com.qiren.project.ui.core.Intend;
import com.qiren.project.ui.core.PageControlCenter;
import com.qiren.project.ui.core.PageRequest;
import com.qiren.project.util.CoreUtils;
import com.qiren.project.util.CourseConstants;

import javax.swing.*;
import java.awt.*;

/**
 * List in page {@link ViewCoursePlanPage}
 */
public class PlanListItem {
    private JButton regisButton;
    private JPanel buttonPanel;
    private JLabel infoLabel;
    private JPanel mainPanel;

    private UserService userService = ServiceBuilder
            .getInstance().build(UserService.class);
    private CoursePlanService coursePlanService = ServiceBuilder
            .getInstance().build(CoursePlanService.class);
    private CoursePlan coursePlan;
    private JFrame frame;

    public PlanListItem(JFrame frame, CoursePlan coursePlan) {
        this.frame = frame;
        this.coursePlan = coursePlan;
        init();
    }

    private void init() {
        String html = """
                <html>
                <b>Name:&nbsp;</b>%replace1%<br>
                <b>Lecturer:&nbsp;</b>%replace2%<br>
                <b>Weekdays:&nbsp;</b>%replace3%<br>
                <b>fromTime:&nbsp;</b>%replace4%<br>
                <b>toTime:&nbsp;</b>%replace5%<br>
                <b>status:&nbsp;</b>%replace6%<br>
                </html>
                """;
        infoLabel.setText(
                CoreUtils.customFormat(
                        html, coursePlan.getFkCourse(),
                        coursePlan.getFkStaff(), coursePlan.getWeekDay(),
                        coursePlan.getFromTime(), coursePlan.getToTime(),
                        CourseConstants.covertStatus(coursePlan.getStatus().substring(0, 1))
                ));
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.X_AXIS));
        buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));
        if (userService.isStaff()) {
            // staff
            regisButton.setText("View Registration");
            regisButton.addActionListener(e -> {
                // go to view registration
                Intend intend = new Intend(PageRequest.PAGE_CHANGE_REQUEST,
                        PageRequest.VIEW_PLAN_PAGE, PageRequest.REGIS_PLAN_PAGE);
                intend.addExtra("course", coursePlan.getFkCourse());
                PageControlCenter.getInstance().sendPageRequest(intend);
            });
            JButton syllabusButton = new JButton("View Schedule");
            syllabusButton.addActionListener(e -> {
                // go to schedule page
                Intend intend = new Intend(
                        PageRequest.PAGE_CHANGE_REQUEST, PageRequest.VIEW_PLAN_PAGE, PageRequest.VIEW_SYLLABUS_PAGE);
                intend.addExtra("course", coursePlan.getPlanId() + "");
                intend.addExtra("semester", coursePlan.getFkSem());
                PageControlCenter.getInstance().sendPageRequest(intend);
            });
            buttonPanel.add(syllabusButton);
            JButton cancelButton = new JButton("      Cancel         ");
            cancelButton.addActionListener(e -> {
                int res = JOptionPane.showConfirmDialog(frame, "Are you sure to cancel this page?");
                if (res == 0) {
                    coursePlanService.cancelPlan(coursePlan.getUid());
                }
            });
            buttonPanel.add(cancelButton);
        } else {
            // student
            regisButton.setText("      Continue      ");
            regisButton.addActionListener(e -> {
                // register for this class
                JOptionPane.showMessageDialog(frame,
                        new RegisPage(frame, coursePlan).getMainPanel(),
                        "Registration Details",
                        JOptionPane.INFORMATION_MESSAGE);
            });
//            JButton syllabusButton = new JButton("View Syllabus");
//            syllabusButton.addActionListener(e -> {
//                // go to syllabus page
//            });
//            buttonPanel.add(syllabusButton);
        }
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        infoLabel = new JLabel();
        infoLabel.setText("<html> <b>CRN:</b>INFO 5100<br> <b>Name:</b>Application Engineering and Development<br> <b>Subject:</b>INFO<br> <b>Credits:</b>4<br> </html> ");
        mainPanel.add(infoLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(buttonPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        regisButton = new JButton();
        regisButton.setText("View Registration");
        buttonPanel.add(regisButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    //    private void createUIComponents() {
//        buttonPanel = new JPanel();
//        buttonPanel.setLayout(new GridLayout(0, 1, 20, 20));
//    }
}
